##**3**. Del dataset elegido realice la imputación por columnas sin scikit-learn.

In [2]:
import os
from google.colab import drive
drive.mount('/content/drive')
#cambiar el directorio de trabajo actual
os.chdir('/content/drive/MyDrive/data')
!pwd

Mounted at /content/drive
/content/drive/MyDrive/data


In [3]:
import pandas as pd
import numpy as np
#lectura de datos por categoria
datos=pd.read_csv("heart_attack_dataset.csv")
datos.head(100)
#datos.sample(n=10)

Age  Cholesterol  Heart Rate  Diabetes  Family History  Smoking  Obesity  \
0    67          208          72         0               0        1        0   
1    21          389          98         1               1        1        1   
2    21          324          72         1               0        0        0   
3    84          383          73         1               1        1        0   
4    66          318          93         1               1        1        1   
..  ...          ...         ...       ...             ...      ...      ...   
95   83          240          69         1               0        1        1   
96   27          237          65         1               1        1        1   
97   31          333         106         1               0        0        0   
98   82          216         109         1               1        1        1   
99   28          276          65         1               0        1        1   

    Alcohol Consumption  Previous Heart Problems  Medication Use  Stress Level  
0                     0                        0               0             9  
1                     1                        1               0             1  
2                     0                        1               1             9  
3                     1                        1               0             9  
4                     0                        1               0             6  
..                  ...                      ...             ...           ...  
95                    1                        0               1             6  
96                    0                        1               0            10  
97                    0                        1               0             2  
98                    1                        0               0             6  
99                    1                        1               1             7  

[100 rows x 11 columns]

In [4]:
from sklearn.impute import SimpleImputer
import numpy as np
datos_num=datos[['Age','Cholesterol','Heart Rate','Diabetes','Family History','Smoking','Obesity','Alcohol Consumption', 'Previous Heart Problems', 'Medication Use', 'Stress Level']]
array1=np.array(datos_num)

# array1 = np.asarray([[1,2,np.nan], [np.nan, 2,3], [4,6,8]])
imputacion = SimpleImputer(missing_values = np.nan, strategy = 'mean')
array2 = imputacion.fit_transform(array1)
print(array1)
print(array2)
" -- Escalado"

print('-- mostrar Escalado')
from sklearn.preprocessing import StandardScaler
escalado = StandardScaler()
array3 = escalado.fit_transform(array2)
print(array3)


" -- Normalizado"
print('-- mostrar Normalizado')
from sklearn.preprocessing import Normalizer
preprocesar = Normalizer()
array4 = preprocesar.fit_transform(array2)
print(array4)

[[ 67 208  72 ...   0   0   9]
 [ 21 389  98 ...   1   0   1]
 [ 21 324  72 ...   1   1   9]
 ...
 [ 19 208  56 ...   1   1   6]
 [ 80 196  75 ...   0   1   8]
 [ 88 241  78 ...   1   0   7]]
[[ 67. 208.  72. ...   0.   0.   9.]
 [ 21. 389.  98. ...   1.   0.   1.]
 [ 21. 324.  72. ...   1.   1.   9.]
 ...
 [ 19. 208.  56. ...   1.   1.   6.]
 [ 80. 196.  75. ...   0.   1.   8.]
 [ 88. 241.  78. ...   1.   0.   7.]]
-- mostrar Escalado
[[ 0.60317831 -0.64937239 -0.13722255 ... -0.98214733 -0.9782224
   1.26558238]
 [-1.50517863  1.59880058  1.14807223 ...  1.01817719 -0.9782224
  -1.54807426]
 [-1.50517863  0.79144564 -0.13722255 ...  1.01817719  1.02226242
   1.26558238]
 ...
 [-1.59684632 -0.64937239 -0.92817318 ...  1.01817719  1.02226242
   0.21046114]
 [ 1.19901832 -0.79842253  0.0110807  ... -0.98214733  1.02226242
   0.9138753 ]
 [ 1.56568909 -0.2394845   0.15938394 ...  1.01817719 -0.9782224
   0.56216822]]
-- mostrar Normalizado
[[0.29097725 0.90333236 0.31269197 ... 0.       